### ISSUE TITLE
Compatibility with docker

### ISSUE THREAD

**Issue by tibotiber** [wk-j/vscode-webpack-progress#3]
Hi! 
Your extension looks great. Does it support webpack running in a docker container? How would I go about setting this up?
Thank you.

**Comment by wk-j** [comment]
@tibotiber 

Can you provide more details
I don't see the different between webpack under docker and normal webpack.

**Comment by tibotiber** [comment]
Not sure what details you need? 
When I try running the webpack dev server locally I have the loading percentage as well as check when webpack is loaded. However if I run the webpack dev server in docker, it doesn't seem to be detected at all.

**Comment by wk-j** [comment]
OK I get it

In your case webpack and vscode is loading difference status file.
Status file is `${os.tmpdir()}/webpack-progress` 

Like this
`/var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/webpack-progress`

if you map tmpdir() of docker to same place of host machine it could work.

**Comment by tibotiber** [comment]
Thank you. That was indeed the issue.
In case it can be useful for anyone else, on macOS, I added this to my `docker-compose.yml` under `volumes`: `- /private/$TMPDIR/webpack-progress:/usr/src/app/webpack-progress:rw`. with `/usr/src/app/` the mount point for your working directory.
